on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  # Cancel running job if new commits are pushed
  group: >
    ${{ github.workflow }}-
    ${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test petsctools
    runs-on: ubuntu:latest
    env:
      PETSC_DIR: /usr/lib/petscdir/petsc3.19/s390x-linux-gnu-real/
    steps:
      - uses: actions/checkout@v4
        with:
          # Download petsctools into a subdirectory not called 'petsctools' to
          # make sure that the package installs correctly. Otherwise
          # 'import petsctools' could work even if the installation failed
          # because it is a subdirectory.
          path: petsctools-repo

      - uses: actions/setup-python
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install petsc-dev python3-venv

      - name: Install petsctools
        run: |
          python3 -m venv --system-site-packages venv-petsctools
          . venv-petsctools/bin/activate
          pip install ./petsctools-repo
          pip list

      - name: Run tests without petsc4py
        run: |
          . venv-petsctools/bin/activate
          python -c "import petsctools"

      - name: Install petsc4py
        run: |
          sudo apt-get -y install python3-petsc4py 

      - name: Run tests with petsc4py
        run: |
          . venv-petsctools/bin/activate
          python -c "import petsctools"
