name: Test pull request

on:
  pull_request:
    types: [ opened, synchronize, reopened, edited ]

jobs:
  test:
    uses: ./.github/workflows/core.yml
    with:
      source_ref: ${{ github.ref }}
      target_branch: ${{ github.base_ref }}
      # UNDO ME
      deploy_website: true
    secrets: inherit
