name: Push dist to PyPI

on:
  workflow_call:
    inputs:
      ref:
        description: The Git ref to checkout
        type: string
        required: true

  workflow_dispatch:
    inputs:
      source_ref:
        description: The Git ref to checkout
        type: string
        required: true

jobs:
  build:
    name: Build dist files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build petsctools
        run: |
          pip install build
          python -m build .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  pypi:
    name: Push dist to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
